### ISSUE TITLE
Unable to extract views field

### ISSUE THREAD

**Issue by NoteToSelf** [NoteToSelf/immo-kleinanzeigen#15]

**Comment by OSchwark** [comment]
"views" are not loaded in initial html but are injected from "api" via js. URL seems to be this one: https://www.kleinanzeigen.de/s-vac-inc-get.json?adId=2278846789

**Comment by OSchwark** [comment]
my first try to call this api failed (request hangs forever). Seems that there is a protection in place (maybe use cookie?)

this hangs:
```print(requests.get(f'https://www.kleinanzeigen.de/s-vac-inc-get.json?adId=2278846789').json())```

**Comment by OSchwark** [comment]
changing the user-agent does the trick:
```    
headers = {
     'User-Agent': 'My User Agent 1.0'
 }
print(requests.get('https://www.kleinanzeigen.de/s-vac-inc-get.json?adId=2437330673', headers=headers).json()['numVisits'])
```
