### ISSUE TITLE
Http 429 Too Many Requests when calling views API

### ISSUE THREAD

**Issue by NoteToSelf** [NoteToSelf/immo-kleinanzeigen#19]

**Comment by NoteToSelf** [comment]
Scrapping to fast causing HTTP 429 Too Many Requests response on the views API

![Image](https://github.com/NoteToSelf/immo-kleinanzeigen/assets/9107159/9c8d230a-91d7-4352-a0c0-2f6728f09af3)

**Comment by OSchwark** [comment]
its not a bug, its a feature 😅 
I need to check if it contains the `Retry-After`-Header. Nevertheless it could be hard to handle this in multithreading environment

**Comment by NoteToSelf** [comment]
https://docs.scrapy.org/en/latest/topics/practices.html
