### ISSUE TITLE
Leave fields null if empty and not ''

### ISSUE THREAD

**Issue by NoteToSelf** [NoteToSelf/immo-kleinanzeigen#21]

**Comment by OSchwark** [comment]
you want to distinguish between "attribute was found but is empty" and "attribute was not found at all", right?
Seems like it is not (easily) possible ...: https://stackoverflow.com/questions/11379300/csv-reader-behavior-with-none-and-empty-string

**Comment by NoteToSelf** [comment]
I don't think we need to distinguish between "attribute was found but is empty" and "attribute was not found at all".
If there is no information wether not found or value is empty, we just assign None for null value in database. 
If we do have some information, just return value with correct format.
